### ISSUE TITLE
New test: as a dapp developer, I can get events for my contracts

### ISSUE THREAD

**Issue by sreuland** [stellar/system-test#2]
### What problem does your feature solve?

lack of automated e2e coverage of the soroban platform retrieval of contract events at the dapp use case level

### What would you like to see?
new automated test for e2e case:

as a dapp developer, I can get events for my contracts

test should be packaged in docker and as a go test and asserts on configurable versions of cli, rpc, contracts, network work together and emit contract events.

Need to identify what filter parameters for events the test should exercise:
* 'by contract id'
* 'by event topic' 
* 'by chronologic event id'

**Comment by jcx120** [comment]
Currently all Go code/repo

**Comment by sreuland** [comment]
closing, this was implemented per https://github.com/stellar/system-test/issues/40
