### ISSUE TITLE
Existing tests should pass with newer ScVal model

### ISSUE THREAD

**Issue by tsachiherman** [stellar/system-test#41]
### What ?
Verify that any references to ScVal in system test are updated to conform to newer ScVal model.
Fix any failures or regressions due to the new ScVal model from core.
Should be able to run system tests against latest version of pre-release core git ref that has newer ScVal and pass.

### Epic

https://github.com/stellar/soroban-tools/issues/471

**Comment by paulbellamy** [comment]
I *think* the only place we deal with scvals directly in this repo is in `invoke.ts`
